/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifiedCallerIdRouteImport } from './routes/verified-caller-id'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MSurveyReportsRouteImport } from './routes/m-survey-reports'
import { Route as MSurveyRouteImport } from './routes/m-survey'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HelpdeskRouteImport } from './routes/helpdesk'
import { Route as EsimRouteImport } from './routes/esim'
import { Route as CreateCampaignRouteImport } from './routes/create-campaign'
import { Route as CrbtRouteImport } from './routes/crbt'
import { Route as BulkEmailRouteImport } from './routes/bulk-email'
import { Route as ActivityLogsRouteImport } from './routes/activity-logs'
import { Route as IndexRouteImport } from './routes/index'

const VerifiedCallerIdRoute = VerifiedCallerIdRouteImport.update({
  id: '/verified-caller-id',
  path: '/verified-caller-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MSurveyReportsRoute = MSurveyReportsRouteImport.update({
  id: '/m-survey-reports',
  path: '/m-survey-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MSurveyRoute = MSurveyRouteImport.update({
  id: '/m-survey',
  path: '/m-survey',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskRoute = HelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => rootRouteImport,
} as any)
const EsimRoute = EsimRouteImport.update({
  id: '/esim',
  path: '/esim',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCampaignRoute = CreateCampaignRouteImport.update({
  id: '/create-campaign',
  path: '/create-campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CrbtRoute = CrbtRouteImport.update({
  id: '/crbt',
  path: '/crbt',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkEmailRoute = BulkEmailRouteImport.update({
  id: '/bulk-email',
  path: '/bulk-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogsRoute = ActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/bulk-email': typeof BulkEmailRoute
  '/crbt': typeof CrbtRoute
  '/create-campaign': typeof CreateCampaignRoute
  '/esim': typeof EsimRoute
  '/helpdesk': typeof HelpdeskRoute
  '/integrations': typeof IntegrationsRoute
  '/m-survey': typeof MSurveyRoute
  '/m-survey-reports': typeof MSurveyReportsRoute
  '/reports': typeof ReportsRoute
  '/verified-caller-id': typeof VerifiedCallerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/bulk-email': typeof BulkEmailRoute
  '/crbt': typeof CrbtRoute
  '/create-campaign': typeof CreateCampaignRoute
  '/esim': typeof EsimRoute
  '/helpdesk': typeof HelpdeskRoute
  '/integrations': typeof IntegrationsRoute
  '/m-survey': typeof MSurveyRoute
  '/m-survey-reports': typeof MSurveyReportsRoute
  '/reports': typeof ReportsRoute
  '/verified-caller-id': typeof VerifiedCallerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/bulk-email': typeof BulkEmailRoute
  '/crbt': typeof CrbtRoute
  '/create-campaign': typeof CreateCampaignRoute
  '/esim': typeof EsimRoute
  '/helpdesk': typeof HelpdeskRoute
  '/integrations': typeof IntegrationsRoute
  '/m-survey': typeof MSurveyRoute
  '/m-survey-reports': typeof MSurveyReportsRoute
  '/reports': typeof ReportsRoute
  '/verified-caller-id': typeof VerifiedCallerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-logs'
    | '/bulk-email'
    | '/crbt'
    | '/create-campaign'
    | '/esim'
    | '/helpdesk'
    | '/integrations'
    | '/m-survey'
    | '/m-survey-reports'
    | '/reports'
    | '/verified-caller-id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-logs'
    | '/bulk-email'
    | '/crbt'
    | '/create-campaign'
    | '/esim'
    | '/helpdesk'
    | '/integrations'
    | '/m-survey'
    | '/m-survey-reports'
    | '/reports'
    | '/verified-caller-id'
  id:
    | '__root__'
    | '/'
    | '/activity-logs'
    | '/bulk-email'
    | '/crbt'
    | '/create-campaign'
    | '/esim'
    | '/helpdesk'
    | '/integrations'
    | '/m-survey'
    | '/m-survey-reports'
    | '/reports'
    | '/verified-caller-id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityLogsRoute: typeof ActivityLogsRoute
  BulkEmailRoute: typeof BulkEmailRoute
  CrbtRoute: typeof CrbtRoute
  CreateCampaignRoute: typeof CreateCampaignRoute
  EsimRoute: typeof EsimRoute
  HelpdeskRoute: typeof HelpdeskRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MSurveyRoute: typeof MSurveyRoute
  MSurveyReportsRoute: typeof MSurveyReportsRoute
  ReportsRoute: typeof ReportsRoute
  VerifiedCallerIdRoute: typeof VerifiedCallerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verified-caller-id': {
      id: '/verified-caller-id'
      path: '/verified-caller-id'
      fullPath: '/verified-caller-id'
      preLoaderRoute: typeof VerifiedCallerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m-survey-reports': {
      id: '/m-survey-reports'
      path: '/m-survey-reports'
      fullPath: '/m-survey-reports'
      preLoaderRoute: typeof MSurveyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m-survey': {
      id: '/m-survey'
      path: '/m-survey'
      fullPath: '/m-survey'
      preLoaderRoute: typeof MSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk': {
      id: '/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof HelpdeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esim': {
      id: '/esim'
      path: '/esim'
      fullPath: '/esim'
      preLoaderRoute: typeof EsimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-campaign': {
      id: '/create-campaign'
      path: '/create-campaign'
      fullPath: '/create-campaign'
      preLoaderRoute: typeof CreateCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crbt': {
      id: '/crbt'
      path: '/crbt'
      fullPath: '/crbt'
      preLoaderRoute: typeof CrbtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-email': {
      id: '/bulk-email'
      path: '/bulk-email'
      fullPath: '/bulk-email'
      preLoaderRoute: typeof BulkEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-logs': {
      id: '/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof ActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityLogsRoute: ActivityLogsRoute,
  BulkEmailRoute: BulkEmailRoute,
  CrbtRoute: CrbtRoute,
  CreateCampaignRoute: CreateCampaignRoute,
  EsimRoute: EsimRoute,
  HelpdeskRoute: HelpdeskRoute,
  IntegrationsRoute: IntegrationsRoute,
  MSurveyRoute: MSurveyRoute,
  MSurveyReportsRoute: MSurveyReportsRoute,
  ReportsRoute: ReportsRoute,
  VerifiedCallerIdRoute: VerifiedCallerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
